#!/usr/bin/env python
"""Generate docs/TOOLS.md from the live tool registry so the reference never drifts."""

from __future__ import annotations

import os
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))
os.environ.setdefault("LLM_PROVIDER", "mock")
os.environ.setdefault("FS_INDEX_ON_STARTUP", "false")

from app.core.config import get_settings  # noqa: E402
from app.plugins.loader import PluginManager  # noqa: E402
from app.security.permissions import DEFAULT_POLICY  # noqa: E402
from app.tools.base import ToolRegistry  # noqa: E402


def main() -> None:
    settings = get_settings()
    registry = ToolRegistry()
    pm = PluginManager(registry, settings, ROOT / "plugins")
    pm.load_builtin()
    by_cat = defaultdict(list)
    for t in registry.all():
        by_cat[t.category].append(t)

    lines = ["# Tools and permissions", "",
             "Generated by `python scripts/gen_tool_docs.py` from the tool registry.", "",
             "Risk levels: READ_ONLY < SAFE < SENSITIVE < DANGEROUS < BLOCKED. A tool's level may be refined per call "
             "(e.g. the terminal classifies each command; `write_file` is DANGEROUS when overwriting). "
             "\"Confirm\" means the tool always asks regardless of policy. Policy per category lives in "
             "`backend/config/permissions.yaml`.", ""]
    lines += ["## Default policy", "", "| Category | READ_ONLY | SAFE | SENSITIVE | DANGEROUS | BLOCKED |", "|---|---|---|---|---|---|"]
    for cat in sorted(DEFAULT_POLICY):
        p = DEFAULT_POLICY[cat]
        lines.append(f"| {cat} | {p['READ_ONLY']} | {p['SAFE']} | {p['SENSITIVE']} | {p['DANGEROUS']} | {p['BLOCKED']} |")
    lines.append("")
    for cat in sorted(by_cat):
        plugin = pm.plugins.get(cat)
        lines += [f"## {cat}", ""]
        if plugin:
            lines += [plugin.description, ""]
            if plugin.configuration:
                lines += ["Configuration: " + ", ".join(f"`{k}`" for k in plugin.configuration), ""]
        lines += ["| Tool | Risk | Confirm | Cloud | Description |", "|---|---|---|---|---|"]
        for t in sorted(by_cat[cat], key=lambda x: x.name):
            lines.append(f"| `{t.name}` | {t.risk_level.value} | {'yes' if t.requires_confirmation else ''} | "
                         f"{'yes' if t.available_in_cloud else 'no'} | {t.description.replace('|', '/')} |")
        lines.append("")
        for t in sorted(by_cat[cat], key=lambda x: x.name):
            params = t.schema()["function"]["parameters"].get("properties", {})
            if params:
                sig = ", ".join(f"{k}: {v.get('type', 'any')}" for k, v in params.items())
                lines.append(f"- `{t.name}({sig})`")
        lines.append("")
    out = ROOT / "docs" / "TOOLS.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out} ({len(registry)} tools, {len(by_cat)} categories)")


if __name__ == "__main__":
    main()
